CREATE TABLE DEPOSIT (
    ACTNO VARCHAR2(5),
    CNAME VARCHAR2(18),
    BNAME VARCHAR2(18),
    AMOUNT NUMBER(8,2),
    ADATE DATE
);

-- Create BRANCH table
CREATE TABLE BRANCH (
    BNAME VARCHAR2(18),
    CITY VARCHAR2(18)
);

-- Insert sample data in DEPOSIT table
INSERT INTO DEPOSIT VALUES ('101', 'ANIL', 'ANDHERI', 7000, TO_DATE('01-JAN-95', 'DD-MON-YY'));
INSERT INTO DEPOSIT VALUES ('102', 'SUNIL', 'VIRAR', 5000, TO_DATE('15-JUL-96', 'DD-MON-YY'));
INSERT INTO DEPOSIT VALUES ('103', 'MEHUL', 'KAROLBAGH', 3500, TO_DATE('12-NOV-95', 'DD-MON-YY'));
INSERT INTO DEPOSIT VALUES ('104', 'MADHURI', 'CHANDI', 1200, TO_DATE('17-DEC-95', 'DD-MON-YY'));
INSERT INTO DEPOSIT VALUES ('105', 'PRAMOD', 'M.G.ROAD', 3000, TO_DATE('27-MAR-96', 'DD-MON-YY'));
INSERT INTO DEPOSIT VALUES ('106', 'SANDIP', 'ANDHERI', 2000, TO_DATE('31-MAR-96', 'DD-MON-YY'));
INSERT INTO DEPOSIT VALUES ('107', 'SHIVANI', 'VIRAR', 1000, TO_DATE('05-SEP-96', 'DD-MON-YY'));
INSERT INTO DEPOSIT VALUES ('108', 'KRANTI', 'NEHRU PLACE', 5000, TO_DATE('02-JUL-95', 'DD-MON-YY'));
INSERT INTO DEPOSIT VALUES ('109', 'MINU', 'POWAI', 7000, TO_DATE('10-AUG-96', 'DD-MON-YY'));

-- Insert sample data in BRANCH table
INSERT INTO BRANCH VALUES ('ANDHERI', 'BOMBAY');
INSERT INTO BRANCH VALUES ('VIRAR', 'BOMBAY');
INSERT INTO BRANCH VALUES ('KAROLBAGH', 'DELHI');
INSERT INTO BRANCH VALUES ('CHANDI', 'DELHI');
INSERT INTO BRANCH VALUES ('M.G.ROAD', 'BANGLORE');
INSERT INTO BRANCH VALUES ('NEHRU PLACE', 'DELHI');
INSERT INTO BRANCH VALUES ('POWAI', 'BOMBAY');
INSERT INTO BRANCH VALUES ('VRCE', 'NAGPUR');

-- ===============================
-- PRACTICAL 2: DDL and DML commands
-- ===============================

-- 1) Create CLIENTS table
CREATE TABLE CLIENTS (
    CNAME VARCHAR2(19),
    CITY VARCHAR2(18)
);

-- 2) Create BORROW table
CREATE TABLE BORROW (
    LOANNO VARCHAR2(5),
    CNAME VARCHAR2(18)
);

-- 3) Modify BORROW table to add columns
ALTER TABLE BORROW ADD (
    BRANCHNAME VARCHAR2(20),
    AMOUNT NUMBER(8,2),
    PINCODE VARCHAR2(6)
);

-- 4) Change datatype of BRANCHNAME
ALTER TABLE BORROW MODIFY BRANCHNAME VARCHAR2(18);

-- 5) Rename BRANCHNAME to BNAME
ALTER TABLE BORROW RENAME COLUMN BRANCHNAME TO BNAME;

-- 6) Delete PINCODE column
ALTER TABLE BORROW DROP COLUMN PINCODE;

-- 7) Rename CLIENTS table to CUSTOMERS
RENAME CLIENTS TO CUSTOMERS;

-- 8) Insert values in CUSTOMERS table
INSERT INTO CUSTOMERS VALUES ('ANIL', 'BOMBAY');
INSERT INTO CUSTOMERS VALUES ('SUNIL', 'DELHI');
INSERT INTO CUSTOMERS VALUES ('MEHUL', 'BARODA');
INSERT INTO CUSTOMERS VALUES ('MANDAR', 'PATNA');
INSERT INTO CUSTOMERS VALUES ('MADHURI', 'NAGPUR');
INSERT INTO CUSTOMERS VALUES ('PRAMOD', 'NAGPUR');
INSERT INTO CUSTOMERS VALUES ('SANDIP', 'SURAT');
INSERT INTO CUSTOMERS VALUES ('SHIVANI', 'BOMBAY');
INSERT INTO CUSTOMERS VALUES ('KRANTI', 'BOMBAY');
INSERT INTO CUSTOMERS VALUES ('NAREN', 'BOMBAY');

-- 9) Insert values in BORROW table
INSERT INTO BORROW VALUES ('201', 'ANIL', 'VRCE', 1000);
INSERT INTO BORROW VALUES ('206', 'MEHUL', 'AJNI', 5000);
INSERT INTO BORROW VALUES ('311', 'SUNIL', 'KAROLBAGH', 3000);
INSERT INTO BORROW VALUES ('321', 'MADHURI', 'VRCE', 2000);
INSERT INTO BORROW VALUES ('375', 'PRAMOD', 'VIRAR', 8000);
INSERT INTO BORROW VALUES ('481', 'KRANTI', 'NEHRU PLACE', 3000);

-- 10) Update amount for customers from VRCE branch
UPDATE BORROW SET AMOUNT = AMOUNT * 1.1 WHERE BNAME = 'VRCE';

-- 11) Delete customer with LOANNO 481
DELETE FROM BORROW WHERE LOANNO = '481';

-- ===============================
-- PRACTICAL 3: Data Constraints
-- ===============================

-- 1) Create EMP and DEPT tables
CREATE TABLE EMP (
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4)
);

CREATE TABLE DEPT (
    DEPTNO NUMBER(2),
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13)
);

-- 2) Add constraints to EMP table
ALTER TABLE EMP ADD CONSTRAINT pk_emp PRIMARY KEY (EMPNO);
ALTER TABLE EMP MODIFY ENAME NOT NULL;

-- Add constraints to DEPT table
ALTER TABLE DEPT MODIFY DNAME NOT NULL;
ALTER TABLE DEPT MODIFY LOC NOT NULL;

-- 3) Add columns to EMP table
ALTER TABLE EMP ADD (
    HIREDATE DATE,
    SAL NUMBER(7,2) CHECK (SAL > 0),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2)
);

-- 4) Insert data in EMP table
INSERT INTO EMP VALUES (7369, 'SMITH', 'CLERK', 7902, TO_DATE('17-DEC-80','DD-MON-YY'), 800, NULL, 20);
INSERT INTO EMP VALUES (7499, 'ALLEN', 'SALESMAN', 7698, TO_DATE('20-FEB-81','DD-MON-YY'), 1600, 300, 30);
INSERT INTO EMP VALUES (7521, 'WARD', 'SALESMAN', 7698, TO_DATE('22-FEB-81','DD-MON-YY'), 1250, 500, 30);
INSERT INTO EMP VALUES (7566, 'JONES', 'MANAGER', 7839, TO_DATE('02-APR-81','DD-MON-YY'), 2975, NULL, 20);
INSERT INTO EMP VALUES (7654, 'MARTIN', 'SALESMAN', 7698, TO_DATE('28-SEP-81','DD-MON-YY'), 1250, 1400, 30);
INSERT INTO EMP VALUES (7698, 'BLAKE', 'MANAGER', 7839, TO_DATE('01-MAY-81','DD-MON-YY'), 2850, NULL, 30);
INSERT INTO EMP VALUES (7782, 'CLARK', 'MANAGER', 7839, TO_DATE('09-JUN-81','DD-MON-YY'), 2450, NULL, 10);
INSERT INTO EMP VALUES (7788, 'SCOTT', 'ANALYST', 7566, TO_DATE('19-APR-87','DD-MON-YY'), 3000, NULL, 20);
INSERT INTO EMP VALUES (7839, 'KING', 'PRESIDENT', NULL, TO_DATE('17-NOV-81','DD-MON-YY'), 5000, NULL, 10);
INSERT INTO EMP VALUES (7844, 'TURNER', 'SALESMAN', 7698, TO_DATE('08-SEP-81','DD-MON-YY'), 1500, 0, 30);
INSERT INTO EMP VALUES (7876, 'ADAMS', 'CLERK', 7788, TO_DATE('23-MAY-87','DD-MON-YY'), 1100, NULL, 20);
INSERT INTO EMP VALUES (7900, 'JAMES', 'CLERK', 7698, TO_DATE('03-DEC-81','DD-MON-YY'), 950, NULL, 30);
INSERT INTO EMP VALUES (7902, 'FORD', 'ANALYST', 7566, TO_DATE('03-DEC-81','DD-MON-YY'), 3000, NULL, 20);
INSERT INTO EMP VALUES (7934, 'MILLER', 'CLERK', 7782, TO_DATE('23-JAN-82','DD-MON-YY'), 1300, NULL, 10);

-- 5) Insert data in DEPT table
INSERT INTO DEPT VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT VALUES (20, 'RESEARCH', 'DALLAS');
INSERT INTO DEPT VALUES (30, 'SALES', 'CHICAGO');
INSERT INTO DEPT VALUES (40, 'OPERATIONS', 'BOSTON');

-- 6) Add referential integrity constraints
ALTER TABLE DEPT ADD CONSTRAINT pk_dept PRIMARY KEY (DEPTNO);
ALTER TABLE EMP ADD CONSTRAINT fk_emp_dept FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO);

-- ===============================
-- PRACTICAL 4: Value matching and pattern matching
-- ===============================

-- (1) Describe tables
DESC BORROW;
DESC CUSTOMERS;

-- (2) List all data from DEPOSIT
SELECT * FROM DEPOSIT;

-- (3) List all data from BRANCH
SELECT * FROM BRANCH;

-- (4) Account no and amount of depositors
SELECT ACTNO, AMOUNT FROM DEPOSIT;

-- (5) Name of depositors having amount > 4000
SELECT CNAME FROM DEPOSIT WHERE AMOUNT > 4000;

-- (6) Customers who opened account after 1-12-96
SELECT CNAME FROM DEPOSIT WHERE ADATE > TO_DATE('01-DEC-96', 'DD-MON-YY');

-- (7) Account details between specific dates
SELECT ACTNO, AMOUNT FROM DEPOSIT 
WHERE ADATE BETWEEN TO_DATE('01-JAN-95', 'DD-MON-YY') AND TO_DATE('25-JUL-95', 'DD-MON-YY');

-- (8) Employees in departments 10,20
SELECT EMPNO, ENAME, DEPTNO FROM EMP WHERE DEPTNO IN (10, 20);

-- (9) Name and salary of employees in dept 20 with alias
SELECT ENAME AS "Employee Name", SAL FROM EMP WHERE DEPTNO = 20;

-- LIKE predicate examples:
-- (1) Employee names starting with 'J' and ending with 'S'
SELECT * FROM EMP WHERE ENAME LIKE 'J%S';

-- (2) 5 character names starting with 'SCO'
SELECT ENAME, EMPNO, SAL FROM EMP WHERE ENAME LIKE 'SCO__';

-- (3) Non-null employees with 2nd character 'A' and 5 chars long
SELECT * FROM EMP WHERE ENAME IS NOT NULL AND ENAME LIKE '_A___';

-- (4) Null values with 3rd character 'A'
SELECT * FROM EMP WHERE COMM IS NULL AND ENAME LIKE '__A%';